# statefulset.yaml
#
# This source file is part of the FoundationDB open source project
#
# Copyright 2021 Apple Inc. and the FoundationDB project authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file provides an example of using a statefulset to launch FDB processes
# using the foundationdb-kubernetes image.
#
# This is not a recommended way to run production clusters, but it can be useful
# to test the image in development.
#
# For more information on using this file, see fdbkubernetesmonitor/doc.go
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fdb-kubernetes-example
  labels:
    app: fdb-kubernetes-example
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-example
  replicas: 5
  serviceName: fdb-kubernetes-example
  template:
    metadata:
      labels:
        app: fdb-kubernetes-example
    spec:
      containers:
        - name: foundationdb
          image: foundationdb/foundationdb-kubernetes:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FDB_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FDB_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FDB_CLUSTER_FILE
              value: /var/fdb/data/fdb.cluster
            - name: FDB_PUBLIC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FDB_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FDB_MACHINE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FDB_ZONE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FDB_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - --input-dir
            - /var/fdb/dynamic-conf
          volumeMounts:
            - name: dynamic-conf
              mountPath: /var/fdb/dynamic-conf
            - name: data
              mountPath: /var/fdb/data
      serviceAccountName: fdb-kubernetes-example
      volumes:
        - name: dynamic-conf
          configMap:
            name: fdb-kubernetes-example-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fdb-kubernetes-example-config
data:
  fdb.cluster: ""
  config.json: |
    {
      "serverCount": 0,
      "version": "6.3.15",
      "arguments": [
        {"value": "--cluster_file"},
        {"value": "/var/fdb/data/fdb.cluster"},
        {"value": "--seed_cluster_file"},
        {"value": "/var/fdb/dynamic-conf/fdb.cluster"},
        {"value": "--public_address"},
        {"type": "Concatenate", "values": [
          {"type": "Environment", "source": "FDB_PUBLIC_IP"},
          {"value": ":"},
          {"type": "ProcessNumber", "offset": 4499, "multiplier": 2}
        ]},
        {"value": "--listen_address"},
        {"type": "Concatenate", "values": [
          {"type": "Environment", "source": "FDB_POD_IP"},
          {"value": ":"},
          {"type": "ProcessNumber", "offset": 4499, "multiplier": 2}
        ]},
        {"value": "--datadir"},
        {"type": "Concatenate", "values": [
          {"value": "/var/fdb/data/"},
          {"type": "ProcessNumber"}
        ]},
        {"value": "--class"},
        {"value": "storage"},
        {"value": "--locality_zoneid"},
        {"type": "Environment", "source": "FDB_ZONE_ID"},
        {"value": "--locality_instance-id"},
        {"type": "Environment", "source": "FDB_INSTANCE_ID"},
        {"value": "--locality_process-id"},
        {"type": "Concatenate", "values": [
          {"type": "Environment", "source": "FDB_INSTANCE_ID"},
          {"value": "-"},
          {"type": "ProcessNumber"}
        ]}
      ]
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fdb-kubernetes-example
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdb-kubernetes-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fdb-kubernetes-example
subjects:
- kind: ServiceAccount
  name: fdb-kubernetes-example


